indictranstech/iac_electricals_v13

- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.js
- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.py
[Fix][Add create button with mapping doc code for Blanket order and sales order]
> [Fix][Add create button with mapping doc code for Blanket order and sales order]

- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.py
[Fix][Price Schedule][Adding mapping for diffrent field name in Make sales Order function]
> [Fix][Price Schedule][Adding mapping for diffrent field name in Make sales Order function]

- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.py
[Fix][Server update issue thats why i added error log on code]
>  [Fix][Server update issue thats why i added error log on code]

- iac_electricals/fixtures/custom_field.json
[Fix][Fixtures][mandatory_depends_on: eval:cur_frm.doc.request_type == 'Product Enquiry'][on Product Category on Lead form]
> [Fix][Fixtures][mandatory_depends_on: eval:cur_frm.doc.request_type == 'Product Enquiry'][on Product Category on Lead form]

- iac_electricals/iac_electricals/custom_scripts/lead/lead.js
[Fix][Lead][whe lead save then reload doc]
> [Fix][Lead][whe lead save then reload doc]

- iac_electricals/iac_electricals/custom_scripts/lead/lead.js
- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.py
- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.js
- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.json
- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.py
[Fix][Opportunity][create customer when create Price schedule refrence on opportunity]
> [Fix][Opportunity][create customer when create Price schedule refrence on opportunity]

- iac_electricals/fixtures/property_setter.json
[Fix][Fixture][Packing Slip Items][remove fetch from on item Name]
> [Fix][Fixture][Packing Slip Items][remove fetch from on item Name]

- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.py
[Fix][Opportunity][Server update purpose add print statement]
> [Fix][Opportunity][Server update purpose add print statement]

- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.js
- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.py
[Fix][Opportunity][add throw when not set currency and add control statement when not select currency(if statement) for remove error]
> [Fix][Opportunity][add throw when not set currency and add control statement when not select currency(if statement) for remove error]

- iac_electricals/iac_electricals/custom_scripts/lead/lead.js
[Fix][Lead][Hide fields by code on lead doc (Offer Date & Offer Validity)]
> [Fix][Lead][Hide fields by code on lead doc (Offer Date & Offer Validity)]

- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.js
[Fix][Opportunity][field deleted on doctype and taking fixtures but not reflect on server thats why hide and unmandatory field by code]
> [Fix][Opportunity][field deleted on doctype and taking fixtures but not reflect on server thats why hide and unmandatory field by code]

- iac_electricals/iac_electricals/custom_scripts/opportunity/opportunity.js
[Fix][Opportunity][remove code for hide field on opportunity]
> [Fix][Opportunity][remove code for hide field on opportunity]

- iac_electricals/iac_electricals/report/enquiry_tracker/enquiry_tracker.js
- iac_electricals/iac_electricals/report/enquiry_tracker/enquiry_tracker.json
- iac_electricals/iac_electricals/report/enquiry_tracker/enquiry_tracker.py
[Feature][Script Report][Create New Report Name : Enquiry Tracker for change name for report old name is Export Enquiry Tracker]
>  [Feature][Script Report][Create New Report Name : Enquiry Tracker for change name for report old name is Export Enquiry Tracker]

- iac_electricals/hooks.py
[Fixres][Resolve Marge Conflict][Hook File Chnages]
> [Fixres][Resolve Marge Conflict][Hook File Chnages]

- iac_electricals/hooks.py
- iac_electricals/iac_electricals/custom_scripts/attendance/attendance.py
[Feature][Birthday Reminder][Added Daily scheduler IN hook file]
> [Feature][Birthday Reminder][Added Daily scheduler IN hook file]

- iac_electricals/iac_electricals/doctype/iac_items/iac_items.json
- iac_electricals/iac_electricals/doctype/iac_items/iac_items.py
- iac_electricals/iac_electricals/doctype/inspection_call/inspection_call.js
- iac_electricals/iac_electricals/doctype/inspection_call/inspection_call.json
- iac_electricals/iac_electricals/doctype/inspection_call/inspection_call.py
- iac_electricals/iac_electricals/doctype/inspection_call/test_inspection_call.py
[FEATURE][Doctype created][1 Inspection Call 2 iac items][For inspection purpose on selling]
> [FEATURE][Doctype created][1 Inspection Call 2 iac items][For inspection purpose on selling]

- iac_electricals/iac_electricals/doctype/price_schedule/price_schedule.js
[FIX][Price Schedule][Solve issue when create Price schedule Through Opportunty series not set thats why Price schedule is not save]
> [FIX][Price Schedule][Solve issue when create Price schedule Through Opportunty series not set thats why Price schedule is not save]

- iac_electricals/hooks.py
- iac_electricals/iac_electricals/custom_scripts/quality_inspection/quality_inspection.py
[Feature][Quality Inspection][Average Value Calculation On reading Fields]
> [Feature][Quality Inspection][Average Value Calculation On reading Fields]

- iac_electricals/iac_electricals/custom_scripts/purchase_invoice/purchase_invoice.js
[Feature][Purchase Invoice][Address Display On Purchase Invoice]
> [Feature][Purchase Invoice][Address Display On Purchase Invoice]

- iac_electricals/hooks.py
- iac_electricals/iac_electricals/custom_scripts/item/item.js
- iac_electricals/iac_electricals/custom_scripts/item/item.py
[Fix][Item][Naming series development for item master]
> [Fix][Item][Naming series development for item master]
